// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/orders/orders.proto

package micro_super_lightning_service_orders

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Orders service

func NewOrdersEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Orders service

type OrdersService interface {
	Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Orders_StreamService, error)
	PingPong(ctx context.Context, opts ...client.CallOption) (Orders_PingPongService, error)
}

type ordersService struct {
	c    client.Client
	name string
}

func NewOrdersService(name string, c client.Client) OrdersService {
	return &ordersService{
		c:    c,
		name: name,
	}
}

func (c *ordersService) Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Orders.Call", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ordersService) Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Orders_StreamService, error) {
	req := c.c.NewRequest(c.name, "Orders.Stream", &StreamingRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &ordersServiceStream{stream}, nil
}

type Orders_StreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*StreamingResponse, error)
}

type ordersServiceStream struct {
	stream client.Stream
}

func (x *ordersServiceStream) Close() error {
	return x.stream.Close()
}

func (x *ordersServiceStream) Context() context.Context {
	return x.stream.Context()
}

func (x *ordersServiceStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *ordersServiceStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *ordersServiceStream) Recv() (*StreamingResponse, error) {
	m := new(StreamingResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *ordersService) PingPong(ctx context.Context, opts ...client.CallOption) (Orders_PingPongService, error) {
	req := c.c.NewRequest(c.name, "Orders.PingPong", &Ping{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &ordersServicePingPong{stream}, nil
}

type Orders_PingPongService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Ping) error
	Recv() (*Pong, error)
}

type ordersServicePingPong struct {
	stream client.Stream
}

func (x *ordersServicePingPong) Close() error {
	return x.stream.Close()
}

func (x *ordersServicePingPong) Context() context.Context {
	return x.stream.Context()
}

func (x *ordersServicePingPong) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *ordersServicePingPong) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *ordersServicePingPong) Send(m *Ping) error {
	return x.stream.Send(m)
}

func (x *ordersServicePingPong) Recv() (*Pong, error) {
	m := new(Pong)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Orders service

type OrdersHandler interface {
	Call(context.Context, *Request, *Response) error
	Stream(context.Context, *StreamingRequest, Orders_StreamStream) error
	PingPong(context.Context, Orders_PingPongStream) error
}

func RegisterOrdersHandler(s server.Server, hdlr OrdersHandler, opts ...server.HandlerOption) error {
	type orders interface {
		Call(ctx context.Context, in *Request, out *Response) error
		Stream(ctx context.Context, stream server.Stream) error
		PingPong(ctx context.Context, stream server.Stream) error
	}
	type Orders struct {
		orders
	}
	h := &ordersHandler{hdlr}
	return s.Handle(s.NewHandler(&Orders{h}, opts...))
}

type ordersHandler struct {
	OrdersHandler
}

func (h *ordersHandler) Call(ctx context.Context, in *Request, out *Response) error {
	return h.OrdersHandler.Call(ctx, in, out)
}

func (h *ordersHandler) Stream(ctx context.Context, stream server.Stream) error {
	m := new(StreamingRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.OrdersHandler.Stream(ctx, m, &ordersStreamStream{stream})
}

type Orders_StreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*StreamingResponse) error
}

type ordersStreamStream struct {
	stream server.Stream
}

func (x *ordersStreamStream) Close() error {
	return x.stream.Close()
}

func (x *ordersStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *ordersStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *ordersStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *ordersStreamStream) Send(m *StreamingResponse) error {
	return x.stream.Send(m)
}

func (h *ordersHandler) PingPong(ctx context.Context, stream server.Stream) error {
	return h.OrdersHandler.PingPong(ctx, &ordersPingPongStream{stream})
}

type Orders_PingPongStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Pong) error
	Recv() (*Ping, error)
}

type ordersPingPongStream struct {
	stream server.Stream
}

func (x *ordersPingPongStream) Close() error {
	return x.stream.Close()
}

func (x *ordersPingPongStream) Context() context.Context {
	return x.stream.Context()
}

func (x *ordersPingPongStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *ordersPingPongStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *ordersPingPongStream) Send(m *Pong) error {
	return x.stream.Send(m)
}

func (x *ordersPingPongStream) Recv() (*Ping, error) {
	m := new(Ping)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}
