// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/session_mgr/session_mgr.proto

package micro_super_lightning_service_session_mgr

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for SessionMgr service

func NewSessionMgrEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for SessionMgr service

type SessionMgrService interface {
	GetSession(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	SaveSession(ctx context.Context, in *Session, opts ...client.CallOption) (*Response, error)
	DeleteSession(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (SessionMgr_StreamService, error)
	PingPong(ctx context.Context, opts ...client.CallOption) (SessionMgr_PingPongService, error)
}

type sessionMgrService struct {
	c    client.Client
	name string
}

func NewSessionMgrService(name string, c client.Client) SessionMgrService {
	return &sessionMgrService{
		c:    c,
		name: name,
	}
}

func (c *sessionMgrService) GetSession(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "SessionMgr.GetSession", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionMgrService) SaveSession(ctx context.Context, in *Session, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "SessionMgr.SaveSession", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionMgrService) DeleteSession(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "SessionMgr.DeleteSession", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionMgrService) Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (SessionMgr_StreamService, error) {
	req := c.c.NewRequest(c.name, "SessionMgr.Stream", &StreamingRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &sessionMgrServiceStream{stream}, nil
}

type SessionMgr_StreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*StreamingResponse, error)
}

type sessionMgrServiceStream struct {
	stream client.Stream
}

func (x *sessionMgrServiceStream) Close() error {
	return x.stream.Close()
}

func (x *sessionMgrServiceStream) Context() context.Context {
	return x.stream.Context()
}

func (x *sessionMgrServiceStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *sessionMgrServiceStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *sessionMgrServiceStream) Recv() (*StreamingResponse, error) {
	m := new(StreamingResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *sessionMgrService) PingPong(ctx context.Context, opts ...client.CallOption) (SessionMgr_PingPongService, error) {
	req := c.c.NewRequest(c.name, "SessionMgr.PingPong", &Ping{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &sessionMgrServicePingPong{stream}, nil
}

type SessionMgr_PingPongService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Ping) error
	Recv() (*Pong, error)
}

type sessionMgrServicePingPong struct {
	stream client.Stream
}

func (x *sessionMgrServicePingPong) Close() error {
	return x.stream.Close()
}

func (x *sessionMgrServicePingPong) Context() context.Context {
	return x.stream.Context()
}

func (x *sessionMgrServicePingPong) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *sessionMgrServicePingPong) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *sessionMgrServicePingPong) Send(m *Ping) error {
	return x.stream.Send(m)
}

func (x *sessionMgrServicePingPong) Recv() (*Pong, error) {
	m := new(Pong)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for SessionMgr service

type SessionMgrHandler interface {
	GetSession(context.Context, *Request, *Response) error
	SaveSession(context.Context, *Session, *Response) error
	DeleteSession(context.Context, *Request, *Response) error
	Stream(context.Context, *StreamingRequest, SessionMgr_StreamStream) error
	PingPong(context.Context, SessionMgr_PingPongStream) error
}

func RegisterSessionMgrHandler(s server.Server, hdlr SessionMgrHandler, opts ...server.HandlerOption) error {
	type sessionMgr interface {
		GetSession(ctx context.Context, in *Request, out *Response) error
		SaveSession(ctx context.Context, in *Session, out *Response) error
		DeleteSession(ctx context.Context, in *Request, out *Response) error
		Stream(ctx context.Context, stream server.Stream) error
		PingPong(ctx context.Context, stream server.Stream) error
	}
	type SessionMgr struct {
		sessionMgr
	}
	h := &sessionMgrHandler{hdlr}
	return s.Handle(s.NewHandler(&SessionMgr{h}, opts...))
}

type sessionMgrHandler struct {
	SessionMgrHandler
}

func (h *sessionMgrHandler) GetSession(ctx context.Context, in *Request, out *Response) error {
	return h.SessionMgrHandler.GetSession(ctx, in, out)
}

func (h *sessionMgrHandler) SaveSession(ctx context.Context, in *Session, out *Response) error {
	return h.SessionMgrHandler.SaveSession(ctx, in, out)
}

func (h *sessionMgrHandler) DeleteSession(ctx context.Context, in *Request, out *Response) error {
	return h.SessionMgrHandler.DeleteSession(ctx, in, out)
}

func (h *sessionMgrHandler) Stream(ctx context.Context, stream server.Stream) error {
	m := new(StreamingRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.SessionMgrHandler.Stream(ctx, m, &sessionMgrStreamStream{stream})
}

type SessionMgr_StreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*StreamingResponse) error
}

type sessionMgrStreamStream struct {
	stream server.Stream
}

func (x *sessionMgrStreamStream) Close() error {
	return x.stream.Close()
}

func (x *sessionMgrStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *sessionMgrStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *sessionMgrStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *sessionMgrStreamStream) Send(m *StreamingResponse) error {
	return x.stream.Send(m)
}

func (h *sessionMgrHandler) PingPong(ctx context.Context, stream server.Stream) error {
	return h.SessionMgrHandler.PingPong(ctx, &sessionMgrPingPongStream{stream})
}

type SessionMgr_PingPongStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Pong) error
	Recv() (*Ping, error)
}

type sessionMgrPingPongStream struct {
	stream server.Stream
}

func (x *sessionMgrPingPongStream) Close() error {
	return x.stream.Close()
}

func (x *sessionMgrPingPongStream) Context() context.Context {
	return x.stream.Context()
}

func (x *sessionMgrPingPongStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *sessionMgrPingPongStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *sessionMgrPingPongStream) Send(m *Pong) error {
	return x.stream.Send(m)
}

func (x *sessionMgrPingPongStream) Recv() (*Ping, error) {
	m := new(Ping)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}
