version: '3.5'

services:
  dataredis:
    image: redis:alpine
    container_name: "dataredis"
    environment:
      - REDIS_REPLICATION_MODE=master
    volumes:
      - "./db/redis-data:/var/lib/redis"
      - "./models/conf/redis.conf:/usr/local/etc/redis/redis.conf"
    networks:
      - node-net
    ports:
      - "6379:6379"
    #command: redis-server
    command: redis-server --requirepass sOmE_sEcUrE_pAsS

  datamysql:
    #image: "docker.io/mysql:latest"
    image: mysql:5.7
    #network_mode: "host"
    restart: always
    container_name: "datamysql"
    environment:
      #MYSQL_DATABASE: wordpress
      MYSQL_ROOT_PASSWORD: "yourpassword"
      MYSQL_USER: 'test'
      MYSQL_PASS: 'yourpassword'
    volumes:
      - "./db/mysql:/var/lib/mysql"
      - "./models/conf/my.cnf:/etc/my.cnf"
      - "./models/init:/docker-entrypoint-initdb.d/"
      - "./models/testdata:/home"
    networks:
      - node-net
    ports:
      - "3306:3306"

  #website:
    #restart: always
    #container_name: "website"
    #build: ./website
    #links:
      #- datamysql
      #- dataredis
    #depends_on:
      #- datamysql
      #- dataredis
    #networks:
      #- node-net

  #user_srv:
    #restart: always
    #container_name: "user_srv"
    #build: ./user_srv
    #links:
      #- datamysql
      #- dataredis
    #depends_on:
      #- datamysql
      #- dataredis
      #- website
    #networks:
      #- node-net

networks:
  node-net:
    name: node-net
  outlet-net:
    name: outlet-net
  outlet-backend-net:
    name: outlet-backend-net
