version: '3.5'

services:
  dataredis:
    image: redis:alpine
    container_name: "dataredis"
    environment:
      - REDIS_REPLICATION_MODE=master
    volumes:
      - $PWD/redis-data:/var/lib/redis
      - $PWD/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - outlet-net
    ports:
      - "6379:6379"
    command: redis-server --requirepass sOmE_sEcUrE_pAsS
    networks:
      node_net:
        ipv4_address: 172.28.1.4

# networking for the Redis container
networks:
  node_net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
