app:
  mysql:
    enabled: true
    #url: root:123@(127.0.0.1:3306)/micro_book_mall?charset=utf8&parseTime=true&loc=Asia%2FShanghai
    url: root:yourpassword@(127.0.0.1:3306)/test
    maxIdleConnection: 100
    maxOpenConnection: 130
    connMaxLifetime: 100
